config/routes.rb
Rails.application.routes.draw do
  root to: 'bars#index'
  resources :bars, only: [:index, :new, :create, :show, :edit, :update] do
    resources :reservations, only: [:new, :create, :destroy] do
      member do
        patch'/change_status', to: 'reservations#change_status'
        patch'/change_refuse', to: 'reservations#change_refuse'
      end
    end
    resources :reviews, only: [:create]
  end

  get 'profile', to: 'dashboards#profile'

  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  include PgSearch::Model
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many_attached :photos
  has_many :reviews, dependent: :destroy

  pg_search_scope :search_by_name_description_and_category,
    against: [ :name, :description, :category, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

  multisearchable against: [:name, :description, :category, :address]

  OPENING_DAYS = ['lundi','mardi','mercredi','jeudi', 'vendredi', 'samedi', 'dimanche']
  CATEGORYS = ["Rooftop", "Branché", "Lounge", "Vins", "Latino", "Pub", "Tapas", "Dansant", "Insolite", "Karaoké", "Billard", "Foot", "Club", "Sport", "Piano", "Anniversaire"]
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :bar
  belongs_to :user
  STATUS = ['Pending', 'Accepted', 'Refused']

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :bar
  belongs_to :user
  validates :content, :rating, presence: true
  validates_numericality_of :rating
  validates :rating, :inclusion => { :in => 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
 has_many :bars, dependent: :destroy
 has_many :reservations
 has_one_attached :avatar
 # validates :username, uniqueness: true


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

private

  def configure_permitted_parameters
    update_attrs = [:username, :email, :password, :avatar, :password_confirmation, :current_password]
    devise_parameter_sanitizer.permit :sign_up, keys: update_attrs
    devise_parameter_sanitizer.permit :account_update, keys: update_attrs
  end
  
  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  skip_before_action :authenticate_user!, only:[:index, :show]


  # def search
  #   @bars = Bar.where(params[category: params[:category])
  #   @bar = Bar.where(name: params[:name])
  # end


  def index
    @bars = policy_scope(Bar)

    if params[:query].present?
     @bars = @bars.search_by_name_description_and_category(params[:query])
    end

    @bars = @bars.geocoded

    @markers = @bars.map do |bar|
      {
        lat: bar.latitude,
        lng: bar.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bar: bar })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end

  end

  def new
    @bar = Bar.new
    authorize @bar
  end

  def create
    @bar = Bar.new(bar_params)
    authorize @bar
    @bar.user = current_user
    @bar.opening_days = params[:days].select {|k,v|v =='1'}.keys
    @bar.save
    redirect_to bar_path(@bar)
  end

  def show
    @reservation = Reservation.new
    @review = Review.new
    @bar = Bar.find(params[:id])
    authorize @bar

    @markers =
      [{
        lat: @bar.latitude,
        lng: @bar.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { bar: @bar })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }]
  end

  def edit
    @bar = Bar.find(params[:id])
    authorize @bar
  end

  def update
    @bar = Bar.find(params[:id])
    @bar.update(bar_params)
    redirect_to bar_path(@bar)
    authorize @bar
  end

  private

  def bar_params
    params.require(:bar).permit(:name, :description, :capacity, :address, :category, :opening_hours, :latitude, :longitude, :opening_days, :closing_hours, photos: [])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def profile
    @user = current_user
    skip_authorization
    # @resa = @user.bars.map { |b| [b, b.reservations] }.select { |item| item[1].count > 0 }
    @resa = []
    @user.bars.each do |b|
       if b.reservations.present?
        @resa << b
      end
    end
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @bar = Bar.find(params[:bar_id])
    @reservation = Reservation.new(reservation_params)
    authorize @reservation
    @reservation.date = Date.parse(params[:date])
    @reservation.user = current_user
    @reservation.bar = @bar
    @reservation.status = "Pending"

    if @reservation.save!
      sleep 3
      redirect_to bar_path(@bar)
    else
      render "bars/show"
    end

  end

  def new
     @bar = Bar.find(params[:bar_id])
     @reservation = Reservation.new
     authorize @reservation
   end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.destroy
    redirect_to bar_path(@reservation.bar)
  end

  def change_status
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.status = "Accepted"
    @reservation.save!
    redirect_to profile_path
  end

  def change_refuse
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.status = "Denied"
    @reservation.save!
    redirect_to profile_path
  end

  private

  def reservation_params
    params.require(:reservation).permit(:bar_id, :user_id, :number_of_guest, :hours, :status)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @bar = Bar.find(params[:bar_id])
    @user = current_user
    @review = Review.new
    skip_authorization
  end

  def create
    @bar = Bar.find(params[:bar_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.bar = @bar
    skip_authorization

    if @review.save
      redirect_to bar_path(@bar)
    else
      render "bars/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bars/edit.html.erb
<div class="banner text-light text-center" style="background: linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(0,0,0,0.8) 20%, rgba(0,0,0,0.4) 100%),url('https://images.pexels.com/photos/3201920/pexels-photo-3201920.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'); background-size: cover; min-height: 100vh;">

  <div class="menu row justify-content-between px-5 py-4">
      <div class="column">
        <%= link_to "Checkbar", bars_path , style: "font-size:32px; text-decoration: none; color: white;", data: {turbolinks: 'false'}%>
      </div>
      <div class="column">
        <%= link_to "Create a bar", new_bar_path, class: "btn btn-outline-light" %>
        <%  if !user_signed_in? %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-light" %>
        <% else %>
          <%= link_to 'My dashboard', profile_path, class: "btn btn-outline-light" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/clairebauduin", class: "avatar-large", alt: "avatar-large"%>
        <% end %>
      </div>
    </div>

  <div class="container py-5">
    <h1 style="font-size: 64px" >Update <%= @bar.name %></h1>
    <div class="d-flex card p-4 mt-3 " style="border-radius: 5px; background-color: rgba(255,255,255,0.2);">
      <div class="form-inputs text-center">
      <%= simple_form_for(@bar) do |f| %>
        <div class="form-row justify-content-around">
          <%= f.input :name, class: "col-2" %>
          <%= f.input :address, class: "col-3"%>
          <%= f.input :category, collection: Bar::CATEGORYS, class: "col-2" %>
          <%= f.input :capacity, class: "col-1" %>
        </div>
          <%= f.input :description %>
          <label for="#">Opening days</label>
          <div class="d-flex flex-wrap justify-content-around">
            <%= simple_fields_for :days do |x| %>
              <% Bar::OPENING_DAYS.each do |day| %>
                <%= x.input day.to_sym, as: :boolean %>
              <% end %>
            <% end %>
          </div>
          <div class="form-row justify-content-around">
            <%= f.input :opening_hours, class: "col-2" %>
            <%= f.input :closing_hours, class: "col-2" %>
            <%= f.input :photos, as: :file, input_html: { multiple: true }, class: "col-8" %>
          </div>
        <div class="form-actions text-center mt-4">
          <%= f.button :submit, "Update the bar", class: 'btn btn-outline-light' %>
        </div>
      <% end %>
    </div>
    </div>
  </div>
      <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    The place to drink <i class="fas fa-glass-cheers"></i>
  </div>
</div>
</div>

app/views/bars/index.html.erb
<div class="homepage" style="background-color: black">
  <div class="banner" style="background: linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(0,0,0,0.6) 20%, rgba(0,0,0,0.2) 100%),url('https://res.cloudinary.com/ddw4b3fnq/image/upload/v1582119961/bar_bxoxlk.jpg'); background-size: cover; background-position: center; min-height: 50vh;">
    <div class="menu row justify-content-between px-5 py-4">
      <div class="column">
        <%= link_to "Checkbar", bars_path , style: "font-size:32px; text-decoration: none; color: white;", data: {turbolinks: 'false'}%>
      </div>
      <div class="column">
        <%= link_to "Create a bar", new_bar_path, class: "btn btn-outline-light" %>
        <%  if !user_signed_in? %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-light" %>
        <% else %>
          <%= link_to 'My dashboard', profile_path, class: "btn btn-outline-light" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/clairebauduin", class: "avatar-large", alt: "avatar-large"%>
        <% end %>
      </div>
    </div>

    <div class="container justify-content-center text-center text-light py-3">
      <h1 style="font-size: 80px">Bars</h1>

      <h3>Find the best place to celebrate your event</h3>

        <%= form_tag bars_path, method: :get, class: "d-flex justify-content-center mt-4" do %>
          <div class="col-7 p-0">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Enter a bar name / category / address"
          %>
          </div>
          <div class="col-1 p-0 m-0">
          <%= submit_tag "Search", class: "input-group-prepend btn btn-outline-light" %>
          </div>
        <% end %>
    </div>
  </div>

  <div class="card-container container pb-4" style="background-color: transparent;">
    <div class="cards">
      <% @bars.first(3).each do |bar| %>
        <div class="card-category" style="background-image:linear-gradient(0deg, rgba(0,0,0,0.1474964985994398) 0%, rgba(0,0,0,0.1474964985994398) 100%), url(<%= bar.photo || url_for(bar.photos.first) %>)">
          <h3 class="m-0" id="tag"><%= bar.category %></h3>
          <%= link_to "See More", bar_path(bar), class: "btn btn-outline-light" %>
          <h2 class="m-0" id="name"><%= bar.name %></h2>
          <% if bar.address.size >= 30 %>
            <p class="m-0" id="address"><%= bar.address.first(30) %>...</p>
          <% else %>
            <p class="m-0" id="address"><%= bar.address %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <div id="map"
     style="width: 100%;
     height: 300px; border-radius: 10px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <div class="cards">
      <% if @bars.size > 3 %>
        <% @bars.last(@bars.size - 3).each do |bar| %>
          <div class="card-category" style="background-image:linear-gradient(0deg, rgba(0,0,0,0.1474964985994398) 0%, rgba(0,0,0,0.1474964985994398) 100%), url(<%= bar.photo || url_for(bar.photos.first) %>)">
            <h3 class="m-0" id="tag"><%= bar.category %></h3>
            <%= link_to "See More", bar_path(bar), class: "btn btn-outline-light"%>
            <h2 class="m-0" id="name"><%= bar.name %></h2>
            <% if bar.address.size >= 30 %>
              <p class="m-0" id="address"><%= bar.address.first(30) %>...</p>
            <% else %>
              <p class="m-0" id="address"><%= bar.address %></p>
            <% end %>
          </div>
        <% end %>
      <% else %>
      <% end %>
    </div>
  </div>
      <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    The place to drink <i class="fas fa-glass-cheers"></i>
  </div>
</div>
</div>

app/views/bars/show.html.erb
<div id="parent">
  <div class="banner-show " style="background-image: linear-gradient(180deg, rgba(0,0,0,0) 10%, rgba(0,0,0,0.6264880952380952) 30%,rgba(0,0,0,1) 90%), url(<%= @bar.photo || url_for(@bar.photos.first) %>); height: 50vh;">
    <div class="menu row justify-content-between px-5 py-4">
      <div class="column">
        <%= link_to "Checkbar", bars_path , style: "font-size:32px; text-decoration: none; color: white;", data: {turbolinks: 'false'}%>
      </div>
      <div class="column">
        <%= link_to "Create a bar", new_bar_path, class: "btn btn-outline-light" %>
        <%  if !user_signed_in? %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-light" %>
        <% else %>
          <%= link_to 'My dashboard', profile_path, class: "btn btn-outline-light" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/clairebauduin", class: "avatar-large", alt: "avatar-large"%>
        <% end %>
      </div>
    </div>

    <div class="container text-light" >
      <h1><%= @bar.name %></h1>
      <p class="tag"><%= @bar.category %></p>
      <p><i class="fas fa-map-marker-alt"></i> <%= @bar.address %></p>
      <p><i class="fas fa-users"></i> <%= @bar.capacity %></p>
    </div>
  </div>

  <div class="container text-light">
      <p style="width: 70%;"><%= @bar.description %></p>
      <% if policy(@bar).edit? %>
        <%= link_to edit_bar_path(@bar.id), class: 'pull-right btn btn-outline-light mb-4' do %>
        <i class="fa fa-pencil"></i>Edit this bar
        <% end %>
      <% end %>


    <div class="row ">
      <div class="carousel w-100 col-5 pb-2" style="border-radius: 5px;">

        <% if @bar.photos.one? %>
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" style="border-radius: 5px;">
              <div class="carousel-item active">
                 <%= cl_image_tag @bar.photos[0].key, alt: "First slide", class: "d-block w-100", style: 'object-fit: cover; border-radius: 5px;' %>
              </div>
            </div>
          </div>

        <% elsif @bar.photos.attached? %>
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" style="border-radius: 5px;">
              <div class="carousel-item active">
                 <%= cl_image_tag @bar.photos[0].key, alt: "First slide", class: "d-block w-100 h-100", style: "object-fit: cover; border-radius: 5px;" %>
              </div>
              <div class="carousel-item" style="border-radius: 5px;">
                 <%= cl_image_tag @bar.photos[1].key, alt: "Second slide", class: "d-block w-100 h-100", style: "object-fit: cover; border-radius: 5px;" %>
              </div>
              <div class="carousel-item" style="border-radius: 5px;">
                 <%= cl_image_tag @bar.photos[2].key, alt: "Third slide", class: "d-block w-100 h-100", style: "object-fit: cover; border-radius: 5px;" %>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <% else %>
            <%= image_tag "bar.jpg", alt: "First slide", class: "d-block w-100" %>
        <% end %>
      </div>

      <div id="map" class="container p-0 m-0 col-4"
         style="width: 100%;
         height: 260px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>

    <div class="list-group reviews">
      <h2>Reviews</h2>

      <%= simple_form_for [@bar, @review] do |f| %>
      <div class="row d-flex align-items-top container">
        <%= f.input :rating, collection: 0..5, default: 3,  label: "Rating", label: false%>
        <div id="review-comment"><%= f.input :content, class: "col-10 m-0 input-show", placeholder: "Give a feedback", label: false %></div>
        <%= f.submit class: 'btn btn-outline-light input-show p-3 mb-3' %>
      <% end %>
      </div>

      <% @bar.reviews.each do |review| %>
        <li class="list-group-item reviews">
          <small>
            <p><%= review.user.username %></p>
            <% count = 0 %>
            <% 5.times do %>
              <% if review.rating > count %>
                <i class="fas fa-star"></i>
              <% else %>
                <i class="far fa-star"></i>
              <% end %>
              <% count += 1 %>
            <% end %>
          </small>
          <p><%= review.content %></p>
        </li>
      <% end %>
    </div>

    <div class="d-flex card col-4 offset-4 p-4" id="child-form" style="border-radius: 5px; background-color: rgba(255,255,255,0.4);">
      <h4>Book online!</h4>
      <h4> Open : <%= @bar.opening_days.join(" - ").capitalize %></h4>
      <p>From <%= @bar.opening_hours.hour %>:<%= @bar.opening_hours.min %> to <%= @bar.closing_hours.hour %>:<%= @bar.closing_hours.min %> </p>
      <%= simple_form_for [@bar, @reservation] do |f| %>
        <input name="date" id="flatpickr" class="col-10 offsert-10">
        <%= f.input :hours, as: :time, default: Time.parse('17:00')%>
        <%= f.input :number_of_guest %>
         <%= f.button :submit, class: 'btn btn-outline-light', id: "sweet-alert-demo"%>
      <% end %>
    </div>
  </div>

  <div class="footer mt-5">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      The place to drink <i class="fas fa-glass-cheers"></i>
    </div>
  </div>

</div>

app/views/dashboards/profile.html.erb
<div class="text-light" style="background-color: black;">
  <div class="banner" style="background: linear-gradient(0deg, rgba(0,0,0,1) 0%, rgba(0,0,0,0.6) 20%, rgba(0,0,0,0.2) 100%),url('https://res.cloudinary.com/ddw4b3fnq/image/upload/v1582119961/bar_bxoxlk.jpg'); background-size: cover; background-position: center; min-height: 50vh; position:relative;">
    <div class="menu row justify-content-between px-5 py-4">
      <div class="column">
        <%= link_to "Checkbar", bars_path , style: "font-size:32px; text-decoration: none; color: white;", data: {turbolinks: 'false'}%>
      </div>
      <div class="column">
        <%= link_to "Create a bar", new_bar_path, class: "btn btn-outline-light" %>
        <%  if !user_signed_in? %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-light" %>
        <% else %>
          <%= link_to 'My dashboard', profile_path, class: "btn btn-outline-light" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/clairebauduin", class: "avatar-large", alt: "avatar-large"%>
        <% end %>
      </div>
    </div>

  <div class="container">
    <h1 style="position: absolute; bottom: 40px; font-size:64px;">Welcome on your dashboard, <%= @user.username %>!</h1>
  </div>
  </div>

<div class="container py-5" style="min-height: 50vh;">
  <div class="row">
    <div class="col-6 <%= 'offset-3' if !@resa.size.positive? %>">
      <h2>My bookings</h2>
      <h3>Pending</h3>

      <% @user.reservations.each do |reservation|%>
        <% if reservation.status == "Pending" %>
          <div class="card-category col-12 my-4" style="background-image:linear-gradient(0deg, rgba(0,0,0,0.1474964985994398) 0%, rgba(0,0,0,0.1474964985994398) 100%)">
            <h3 class="m-0 bg-warning" id="tag"><%= reservation.status %></h3>
            <h2 class="m-0" id="bar-card-name"><%= reservation.bar.name %></h2>
            <% if reservation.bar.address.size >= 30 %>
              <p class="m-0" id="bar-address-name"><%= reservation.bar.address.first(30) %>...</p>
            <% else %>
              <p class="m-0" id="bar-address-name"><%= reservation.bar.address %></p>
            <% end %>
            <h2 class="m-0" id="bar-reservation-details"><%= reservation.date %> at <%= reservation.hours.hour %>:<%= reservation.hours.min %> for <%= reservation.number_of_guest %> people</h2>
          </div>
        <% end %>
      <% end %>

          <h3>Accepted</h3>

      <% @user.reservations.each do |reservation|%>
        <% if reservation.status == "Accepted" %>
          <div class="card-category col-12 my-4" style="background-image:linear-gradient(0deg, rgba(0,0,0,0.1474964985994398) 0%, rgba(0,0,0,0.1474964985994398) 100%)">
            <h3 class="m-0 bg-success" id="tag"><%= reservation.status %></h3>
            <h2 class="m-0" id="bar-card-name"><%= reservation.bar.name %></h2>
            <% if reservation.bar.address.size >= 30 %>
              <p class="m-0" id="bar-address-name"><%= reservation.bar.address.first(30) %>...</p>
            <% else %>
              <p class="m-0" id="bar-address-name"><%= reservation.bar.address %></p>
            <% end %>
            <h2 class="m-0" id="bar-reservation-details"><%= reservation.date %> at <%= reservation.hours.hour %>:<%= reservation.hours.min %> for <%= reservation.number_of_guest %> people</h2>
          </div>
        <% end %>
      <% end %>


          <h3>Denied</h3>

      <% @user.reservations.each do |reservation|%>
        <% if reservation.status == "Denied" %>
          <div class="card-category col-12 my-4" style="background-image:linear-gradient(0deg, rgba(0,0,0,0.1474964985994398) 0%, rgba(0,0,0,0.1474964985994398) 100%)">
            <h3 class="m-0 bg-danger" id="tag"><%= reservation.status %></h3>
            <h2 class="m-0" id="bar-card-name"><%= reservation.bar.name %></h2>
            <% if reservation.bar.address.size >= 30 %>
              <p class="m-0" id="bar-address-name"><%= reservation.bar.address.first(30) %>...</p>
            <% else %>
              <p class="m-0" id="bar-address-name"><%= reservation.bar.address %></p>
            <% end %>
            <h2 class="m-0" id="bar-reservation-details"><%= reservation.date %> at <%= reservation.hours.hour %>:<%= reservation.hours.min %> for <%= reservation.number_of_guest %> people</h2>
          </div>
        <% end %>
      <% end %>

    </div>
    <div class="col-6">
      <h2>My booking requests</h2>


        <% @resa.each do |bar|%>
          <div class="card col-12 px-0 mt-4" >
            <%= image_tag bar.photo || url_for(bar.photos.first), style: "height: 200px;object-fit: cover;filter: brightness(0.7)" %>
          </div>
            <div class="card-body text-light text-center px-0">
              <h5 class="card-title" style="font-size: 32px;"><%= bar.name %></h5>
              <% bar.reservations.each do |reservation|%>
              <div class="card-text py-3 my-3" style="box-shadow: 0 0 15px rgba(255,255,255,0.2);border-radius: 5px;">
                <h2 class="m-0" style="font-size: 18px;">Reservation from <%= reservation.user.username %></h2>
                <h2 class="my-2" style="font-size: 24px;"><%= reservation.date %> at <%= reservation.hours.hour %>:<%= reservation.hours.min %> for <%= reservation.number_of_guest %> people</h2>
                <h2 class="m-0" style="font-size: 18px;">Status: <%= reservation.status %></h2>
                <% if reservation.status == 'Pending'%>
                  <%= link_to 'Accept', change_status_bar_reservation_path(reservation.bar.id, reservation.id), method: :patch ,class: "btn btn-outline-success mt-2"%>
                  <%= link_to 'Refuse', change_refuse_bar_reservation_path(reservation.bar.id, reservation.id), method: :patch ,class: "btn btn-outline-danger mt-2"%>
                <% end %>
              </div>
              <% end %>
            </div>
        <% end %>
          </div>
        </div>
    </div>
  </div>

</div>
    <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    The place to drink <i class="fas fa-glass-cheers"></i>
  </div>
</div>